spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/poc_hex
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
#  flyway:
#    baseline-on-migrate: true
#    enabled: true
#    user: postgres
#    password: 19598604
#    baseline-description: "init"
#    baseline-version: 0
#    locations: classpath:db/migration

